pub const ED25519_CODE: u64 = 0xed;
pub const X25519_CODE: u64 = 0xec;
pub mod error;
pub mod key_digest;
pub mod agreement_key;
pub mod key;
pub mod enc_key;
pub mod hash;
pub mod id;
pub mod keypair;
pub mod base;