package idp2p:id;

world idp2p-id-verifier {
    import host: interface {
        use types.{id-proof, idp2p-error};
        verify-proof: func(proof: id-proof, data: list<u8>) -> result<bool, idp2p-error>;
    }
    export id-verifier;
}