[package]
edition = "2021"
name = "idp2p"
version = "0.1.0"

[dependencies]
structopt = "0.3.25"
env_logger = "0.10.0"
dotenv = "0.15.0"
colored = "2.0.0"

[workspace.dependencies]
tokio = { version = "1.32.0", features = ["full"] }
sha2 = { version = "0.10.7", default-features = false }
serde = { version = "1.0.188", default-features = false, features = ["derive", "alloc"] }
idp2p-wasmsg = { version = "0.1.0", path = "core/wasmsg" }

[workspace]
edition = "2021"
members = [
    "utils",
    "core/wasmsg",
    "core/identity",
    "core/sdt",
    "core/ledger"
]