[package]
name = "idp2p"
edition = "2021"

[workspace]
edition = "2021"
members = ["common", "core/id"]

[profile.dev]
lto = true
opt-level = "z"
strip = "symbols"

[dependencies]
wasmtime = "21"
wit-component = "0"
libp2p = "0"

[workspace.dependencies]
rand = "0"
lol_alloc = "0"
hex = "0"
semver = {version = "1", default-features = false, features = ["serde"]}
regex = { version = "1", default-features = false }
anyhow = { version = "1", default-features = false }
serde = { version = "1", default-features = false, features = [
    "derive",
    "alloc",
] }
ciborium = { version = "0", default-features = false }
serde_json = { version = "1", default-features = false }
ed25519-dalek = { version = "2", default-features = false }
sha2 = { version = "*", default-features = false }
multihash = { version = "*", default-features = false, features = ["serde", "alloc"] }
cid = { version = "0.11.1", default-features = false, features = [
    "serde",
    "scale-codec",
] }
chrono = { version = "0", default-features = false, features = [
    "alloc",
    "serde",
    "now"
] }
wit-bindgen = { version = "0", default-features = false, features = ["macros"] }
