[package]
edition = "2021"
name = "idp2p"
version = "0.1.0"

[dependencies]
structopt = "0.3.25"
env_logger = "0.10.0"
dotenv = "0.15.0"
colored = "2.0.0"

[workspace.dependencies]
tokio = { version = "1.32.0", features = ["full"] }
serde = "1.0.188"


[workspace]
edition = "2021"
members = [
    "common",
    "core/identity",
    "core/sdt",
    "core/p2p"
]