[package]
edition = "2021"
name = "idp2p"
version = "0.1.0"

[dependencies]
structopt = "0.3.25"
env_logger = "0.9.0"
dotenv = "0.15.0"
colored = "2.0.0"
libp2p = "0.43.0"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.13.0", features = ["full"] }
idp2p_common = { version = "0.1.0", path = "idp2p-common" }
idp2p_core = { version = "0.1.0", path = "idp2p-core" }
idp2p_node = { version = "0.1.0", path = "idp2p-node" }
idp2p_wallet = { version = "0.1.0", path = "idp2p-wallet" }
idp2p_didcomm = { version = "0.1.0", path = "idp2p-didcomm" }

[workspace]
members = [
    "idp2p-common",
    "idp2p-core",
    "idp2p-didcomm",
    "idp2p-node",
    "idp2p-wallet",
    "idp2p-relay"
]