[package]
edition = "2021"
name = "idp2p-pairsub"
version = "0.1.0"

[dependencies]
log = "0.4.16"
thiserror = "1.0"
libp2p = "0.46.1"
prost = "0.10.4"
async-trait = "0.1.53"

[build-dependencies]
prost-build = "0.10.4"