interface did {
    type bytes = list<u8>;

    variant id-key-kind {
        // current key of current id
        current-key,
        // next key of current id
        next-key,
        // current key of delegate id
        delegation-key(string),
    }

    record persisted-id-proof {
        kind: id-key-kind,
        kid: string,   
        timestamp: s64,
        sig: bytes,
    }

    record persisted-id-inception {
        id: string,
        version: string,
        prior-id: option<string>,
        payload: bytes,
        timestamp: s64,
        proofs: list<persisted-id-proof>,
    } 

    record persisted-id-event {
        id: string,
        version: string,
        kind: string,
        previous: string,
        payload: bytes,
        timestamp: s64,
        proofs: list<persisted-id-proof>,
    } 

    record persisted-id {
        id: string,
        inception: persisted-id-inception,
        events: list<persisted-id-event>,    
    }   
}
