interface error {
    record id-error {
        id: string,
        reason: string,
    }

    variant id-inception-error {
        // general
        invalid-version,
        invalid-timestamp,
        invalid-id(string),
        invalid-payload,
        payload-and-id-not-match,
        threshold-not-match,
        next-threshold-not-match,
        // signers
        invalid-signer(id-error),
        // next signers
        invalid-next-signer(id-error),
        // claims
        invalid-claim(id-error),
        // other
        other(string),
    }

    variant id-event-error {
        // general
        invalid-version,
        invalid-timestamp,
        invalid-event-id(string),
        invalid-payload, 
        payload-and-id-not-match,
        previous-not-match,
        threshold-not-match,
        next-threshold-not-match,
        lack-of-min-proofs,           
        // proofs
        invalid-proof(id-error),
        // signers
        invalid-signer(id-error),
        // next signers
        invalid-next-signer(id-error),     
        // claims
        invalid-claim(id-error),
        // other          
        other(string),
    }
 
}
