interface error {
    record id-error {
        id: string,
        reason: string,
    }

    variant id-inception-error {
        invalid-version,
        invalid-timestamp,
        invalid-id(string),
        invalid-payload,
        payload-and-id-not-match,
        threshold-not-match,
        next-threshold-not-match,
        invalid-signer(id-error),
        invalid-next-signer(id-error),
        invalid-claim(id-error),
        other(string),
    }

    variant id-event-error {
        invalid-version,
        invalid-timestamp,
        invalid-event-id(string),
        invalid-payload, 
        payload-and-id-not-match,
        previous-not-match,
        threshold-not-match,
        next-threshold-not-match,
        lack-of-min-proofs,           
        invalid-proof(id-error),
        invalid-signer(id-error),
        invalid-next-signer(id-error),     
        invalid-claim(id-error),
        other(string),
    }
 
}
