interface model {
    use types.{id-key, id-assertion-method};

    record persisted-id-proof {
        id: string,
        pk: list<u8>,
        sig: list<u8>,
    }

    record persisted-id-inception {
        id: string,
        payload: list<u8>,
    }

    record persisted-id-event {
        id: string,
        payload: list<u8>,
        proofs: list<persisted-id-proof>,
    }

    record id-view {
        // Identifier 
        id: string,
        // Last event id
        event-id: string,
        // Last event time
        event-timestamp: s64,
        // Threshold  
        threshold: u8,
        // Next threshold  
        next-threshold: u8,
        // Current signers
        signers: list<id-key>,
        // CID codec should be 0xed 
        next-signers: list<string>,
        // Peers
        peers: list<string>,
        // Mediators
        mediators: list<string>,
        // Key Agreement
        key-agreements: list<id-key>,
        // Assertion Methods
        assertion-methods: list<id-assertion-method>,
        // States
        states: list<string>,
        // All signers
        all-keys: list<string>,
    }    
}
