interface model {
    use types.{id-signer, id-claim};

    record persisted-id-proof {
        id: string,
        pk: list<u8>,
        sig: list<u8>,
    }

    record persisted-id-inception {
        id: string,
        payload: list<u8>,
    }

    record persisted-id-event {
        id: string,
        payload: list<u8>,
        proofs: list<persisted-id-proof>,
    }

    record id-view {
        // Identifier 
        id: string,
        // Multi signature method   
        threshold: u8,
        // Last event id
        event-id: string,
        // Last event time
        event-timestamp: s64,
        // Current signers
        signers: list<id-signer>,
        // CID codec should be 0xed 
        next-signers: list<string>,
        // Claims
        claims: list<id-claim>,
    }    
}
