interface types {
   record id-proof-envelope {
      id: string,
      purpose: string,
      version: string,
      key-id: string,
      created-at: s64,
      signature: list<u8>
   }

   record id-event-envelope {
      id: string,
      version: string,
      payload: list<u8>,
      proofs: list<id-proof-envelope>
   }

   record id {
      id: string,
      inception: id-event-envelope,
      events: list<id-event-envelope>
   }
}
