interface types {
   record persisted-id-proof {
      id: string,
      version: string,
      key-id: string,
      cryptosuite: string,
      issued-at: s64,
      signature: list<u8>
   }

   record persisted-id-event {
      id: string,
      version: string,
      payload: list<u8>,
      proofs: list<persisted-id-proof>
   }

   record persisted-id {
      id: string,
      inception: persisted-id-event,
      events: list<persisted-id-event>
   }
}
