package idp2p:id;

world idp2p-id {
    use id-types.{persisted-id-inception, persisted-id-event, id-state};

    import verifier: interface {
        use id-types.{id-proof};
        verify-proof: func(proof: id-proof) -> result<bool, string>;
    } 

    /// Verifies an initial identity inception event.
    export verify-inception: func(incepiton: persisted-id-inception) -> result<id-state, string>;

    /// Verifies an identity update event against the existing identity state.
    export verify-event: func(state: id-state, event: persisted-id-event) -> result<id-state, string>;

}
