package idp2p:p2p@0.1.0;
interface handler {

    record id-document {
        id: cid,
        incepiton: persisted-id-inception,
        events: list<persisted-id-event>,
    }

    variant p2p-event {
        resolve,
        provide(id-document),
        notify-event(persisted-id-event),
        notify-message(cid),
    }

    handle: func() -> result<bool, string>;
}

interface id-store {
    type cid = list<u8>;
    get: func(id: cid) -> list<u8>;
    put: func(id: cid, value: list<u8>);
    remove: func(id: cid);
}

world p2p {
    import id-store;
    import handler;
    export handler;
}