[package]
name = "wasmid"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, default-features = false }
sha2 = { version = "0.10.7", default-features = false }
serde_bytes = { version = "0.11.12", default-features = false, features=["alloc"] }

