[package]
edition = "2021"
name = "idp2p-contract"
version = "0.1.0"

[dependencies]
log = "0.4.16"
thiserror = "1.0.38"
tokio = { version = "1.13.0", features = ["full"] }
serde_json = "1.0.96"
serde = "1.0.160"
idp2p-common = { version = "0.1.0", path="../../common"}
