[package]
edition = "2021"
name = "idp2p-protocol"
version = "0.1.0"

[dependencies]
prost = "0.10.3"
libp2p = "0.44.0"
async-trait = "0.1.53"
log = "0.4.16"
thiserror = "1.0"
tokio = { version = "1.13.0", features = ["full"] }

#[build-dependencies]
#prost-build = "0.10.3"