[package]
name = "idp2p-id"
edition = "2021"
description = "IDP2P ID"
version = "0.1.0"
authors = ["adem caglin<adem.caglin@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/idp2p/idp2p"
readme = "README.md"
keywords = ["idp2p", "wasm", "webassembly", "wasmid"]
categories = ["webassembly"]

[dependencies]
regex = { workspace = true }
serde = { workspace = true }
cid ={ workspace = true }
lol_alloc = { workspace = true }
anyhow = { workspace = true }
ed25519-dalek  = { workspace = true }
idp2p-utils ={ path = "../utils", default-features = false}


