[package]
name = "idp2p_core"
version = "0.1.0"
edition = "2018"

[dependencies]
multibase = "0.9.1"
rand = "0.8.0"
ed25519-dalek = "1.0.1"
sha2 = "0.9.8"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
cid = "0.7.0"
x25519-dalek = "1.2.0"
async-trait = "0.1.52"
chrono = "0.4.19"
didcomm-rs = "0.6.6"
uuid = "0.8"
[dependencies.serde_with]
version = "1.11.0"
features = [ "macros" ]