[package]
name = "idp2p_node"
version = "0.1.0"
edition = "2018"
copyright = "2022, Adem Caglin"
authors = ["adem caglin <adem.caglin@gmail.com>"] 

[dependencies]
structopt = "0.3.25"
env_logger = "0.9.0"
async-trait = "0.1.52"
anyhow = "1.0"
warp = "0.3.2"
dotenv = "0.15.0"
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.13.0", features = ["full"] }
libp2p = {version = "0.41.0", features= ["tcp-tokio", "mdns"]}
idp2p_common = { version = "0.1.0", path = "../idp2p-common" }
idp2p_core = { version = "0.1.0", path = "../idp2p-core" }