interface p2p-sender {
    use types.{idp2p-error};

    record idp2p-message-request {
        from-peer-addr: string,
        from-peer-id: string,
        from-id: string,
        message-id: string
    }

    subscribe: func(topic: string) -> result<_, idp2p-error>;

    publish: func(topic: string, payload: list<u8>) -> result<_, idp2p-error>;

    send-message-request: func(payload: idp2p-message-request) -> result<_, idp2p-error>;
}