interface types {
    record idp2p-error {
        code: string,
        message: string,
    }
    
    variant id-claim-value {
        none,
        text(string),
        bytes(list<u8>)
    }

    record id-claim {
        id: string,
        kind: string,
        value: id-claim-value,
        valid-from: string,
        valid-until: option<string>
    }

    record id-signer {
        id: string,
        public-key: list<u8>,
        valid-from: string,
        valid-until: option<string>
    }

    record id-state {
        id: string,
        prior-id: option<string>,
        event-id: string,
        event-timestamp: string,
        threshold: u8,
        next-threshold: u8,
        signers: list<id-signer>,
        current-signers: list<string>,
        next-signers: list<string>,
        claims: list<id-claim>
    }

    record id-proof {
        key-id: string,
        created-at: string,
        signature: list<u8>
    }

    record id-event-receipt {
        id: string,
        version: string,
        created-at: string,
        payload: list<u8>,
        proofs: list<id-proof>,
        external-proofs: list<id-proof-receipt>
    }

    record id-proof-receipt {
        id: string,
        purpose: string,
        version: string,
        key-id: string,
        created-at: string,
        content-id: list<u8>,
        signature: list<u8>
    }

    record did {
        id: string,
        inception: id-event-receipt,
        events: list<id-event-receipt>
    }
}