interface types {
    record idp2p-error {
        code: string,
        message: string,
    }

    record id-claim-value {
        id: string,
        payload: option<list<u8>>,
        valid-from: string,
        valid-until: option<string>
    }

    record id-claim {
        // agreements, assertions, authentications, delegators, mediators, peers, ...
        key: string,
        values: list<id-claim-value>
    }

    record id-signer {
        id: string,
        public-key: list<u8>,
        valid-from: string,
        valid-until: option<string>
    }

    record id-state {
        id: string,
        prior-id: option<string>,
        next-id: option<string>,
        event-id: string,
        event-timestamp: string,
        threshold: u8,
        next-threshold: u8,
        signers: list<id-signer>,
        current-signers: list<string>,
        next-signers: list<string>,
        delegators: list<string>,
        claims: list<id-claim>,
        revoked: bool,
        revoked-at: option<string>
    }

    record id-proof {
        key-id: string,
        created-at: string,
        signature: list<u8>
    }

    record id-event-receipt {
        id: string,
        version: string,
        created-at: string,
        payload: list<u8>,
        proofs: list<id-proof>,
        delegation-proofs: list<id-proof-receipt>
    }

    record id-proof-receipt {
        id: string,
        purpose: string,
        key-id: string,
        created-at: string,
        signature: list<u8>
    }

    record did {
        id: string,
        inception: id-event-receipt,
        events: list<id-event-receipt>
    }
}