package idp2p:core;

world idp2p-message-handler {
    use types.{idp2p-error};

    import store;
    import id-verifier;
    import p2p-sender;

    export handle: func(message: list<u8>) -> result<_, idp2p-error>;
}

world idp2p-id-verifier {
    import host: interface {
        use types.{data-integrity-proof, idp2p-error};
        verify-proof: func(proof: data-integrity-proof, data: list<u8>) -> result<bool, idp2p-error>;
    }
    export id-verifier;
}