package idp2p:wasmid@0.1.0;

interface model { 
    type cid = list<u8>;

    record id-multi-sig {
        m: u8,
        n: u8
    }

    record id-version {
        major: u16,
        minor: u16,
        patch: u16
    }

    record id-key {
        id: cid,
        pk: list<u8>,
    }

    record id-inception {
        id: cid,
        version: id-version,
        m-of-n: id-multi-sig,
        signers: list<cid>,
        state: cid,
    }

    record id-event-proof {
        signer-id: cid,
        signer-pub: list<u8>,
        signature: list<u8>, 
    }

    record id-event {
        id: cid,
        version: id-version,
        previous: cid,
        state: cid,
        signers: option<list<cid>>,
        m-of-n: option<id-multi-sig>,
        proofs: list<id-event-proof>
    }

    record id-state {
        id: cid,                         // id of the identity
        latest-m-of-n: id-multi-sig,     // m of n
        latest-signers: list<cid>,       // signer ids
        latest-event-id: cid,            // last event id
        latest-state: cid,               // state
        states: list<cid>,
        signers: list<cid>,
        events: list<cid>
    }

    record id-inception-input {
        m-of-n: id-multi-sig,     // m of n
        signers: list<list<u8>>,  // signer pub keys
        state: list<u8>           // state
    }
  
    record id-event-input {        
        state: id-state,
        new-state: cid,
        new-signers: option<list<cid>>,
        new-m-of-n: option<id-multi-sig>,
    }

    record id-create-result {
        inception: id-inception,
        signers: list<id-key>,
    }

    record id-create-event-result {
        event: id-event,
        signers: option<list<id-key>>,
    }
}