package idp2p:id@0.1.0;

interface verification { 
    type cid = list<u8>;

    record id-state {
        id: cid,                        
        latest-event-id: cid,
        latest-sdt-root: cid,      
        next-signer-id: cid,       
        next-recovery-id: cid,    
        used-ids: list<cid>,
    }

    record persisted-id-inception {
        id: cid,
        version: string,
        payload: list<u8>,
    }

    record id-proof {
        id: cid,
        pk: list<u8>,
        sig: list<u8>,
    }

    record persisted-id-event {
        id: cid,
        version: string,
        payload: list<u8>,
        proofs: list<id-proof>,
    }

    verify-inception: func(incepiton: persisted-id-inception) -> result<id-state, string>;

    verify-event: func(state: id-state, event: persisted-id-event) -> result<id-state, string>;
}