package idp2p:id@0.1.0;

world idp2p-id {
  import host: interface {
    gen-signer: func(alg: u64) -> list<u8>;
    gen-assertion: func(alg: u64) -> list<u8>;
    gen-agreement: func(alg: u64) -> list<u8>;
  }
  export verification;
}