[package]
edition = "2021"
name = "idp2p-identity"
version = "0.1.0"

[dependencies]
log = "0.4.16"
thiserror = "1.0.38"
prost = "0.11.6"
tokio = { version = "1.13.0", features = ["full"] }
idp2p-common = { version = "0.1.0", path="../../common"}

[build-dependencies]
prost-build = "0.11.9"


