package idp2p:p2p@0.1.0;

world p2p {
     import host: interface {
        get: func(id: cid) -> list<u8>;
        put: func(id: cid, value: list<u8>);
        remove: func(id: cid);
     }
    
     export handle: func(proof: string, root: string) -> result<bool, string>;

     export gen-sdt: func(raw: string) -> result<string, string>;
    
     export query-sdt: func(sdt: string, query: string) -> result<string, string>;
}