interface types {
    type cid = list<u8>;

    record id-snapshot {
        id: cid,   
        state: cid,                      
        event-id: cid,
        event-timestamp: string,
        next-quorum: u8,
        next-signers: list<cid>,       
        used-signers: list<cid>,
        used-states: list<cid>,
    }

    record persisted-id-inception {
        id: cid,
        version: string,
        payload: list<u8>,
    }

    record id-proof {
        id: cid,
        pk: list<u8>,
        sig: list<u8>,
    }

    record persisted-id-event {
        id: cid,
        version: string,
        payload: list<u8>,
        proofs: list<id-proof>,
    }

}