package idp2p:behaviour;

world idp2p-lib {
    import host: interface {
        get: func(key: string) -> result<option<list<u8>>, idp2p-error>;
        call: func(message: list<u8>, state: option<list<u8>>) -> result<list<u8>, idp2p-error>;
    }
    export handle: func(message: list<u8>, state: option<list<u8>>) -> result<list<u8>, idp2p-error>;
}

world idp2p-message-handler {
    import host: interface {
        get: func(key: string) -> result<option<list<u8>>, idp2p-error>;
        put: func(key: string, value: list<u8>) -> result<_, idp2p-error>;
        publish: func(topic: string, payload: list<u8>) -> result<_, idp2p-error>;
        subscribe: func(topic: string) -> result<_, idp2p-error>;
        request: func(addr: string, payload: list<u8>) -> result<_, idp2p-error>;
        response: func(payload: list<u8>) -> result<_, idp2p-error>;
        call: func(message: list<u8>, state: option<list<u8>>) -> result<list<u8>, idp2p-error>;
    }
    export handle: func(message: list<u8>) -> result<_, idp2p-error>;
}

world idp2p-event-handler {
    export handle: func(message: list<u8>) -> result<_, idp2p-error>;
}


/*
   {
     "id": "bacdlfdlf",
     "inception": {
        "id": "bacdlfdlf",
        "payload": "bayyydyydyydydy",
        "signatures": [""],
        "proofs": [""]
     },
     events: [
     {
        "id": "bacdlfdlf",
        "payload": "bayyydyydyydydy",
        "signatures": [""],
        "proofs": [""]
     }
     ]
   }

   verify inception: 

   - get protocol, major, minor and find the component id
   - call(envelope, {id, signatures, proofs}.to_bytes())

   verify event:

   - get protocol, major, minor and find the component id
   - get state from store
   - call(envelope, {id, signatures, proofs, state}.to_bytes())

   handle(envelope, data) {
      envelope = envelope.deserialize();
      match envelope.method {
         proof => {
            {payload} = data;
            proof = envelope.body.deserialize();
            verify(payload, proof)
         }
         inception => {
            {id, signatures, proofs} = data.deserialize();
            verify_signatures(payload, proof)
            verify_proofs(payload, proof)
         }
         event => {
            {id, signatures, proofs} = data.deserialize();
            verify_signatures(payload, proof)
            verify_proofs(payload, proof)
         }
      }
   }
*/