interface types {
    record p2p-error {
        code: string,
        message: string,
    }
 
    record p2p-publish-event {
        topic: string,
        payload: list<u8>
    }
 
    record p2p-request-event {
        peer: string,
        payload: list<u8>
    }
 
    record p2p-response-event {
        payload: list<u8>
    }
 
    record p2p-put-event {
        key: string,
        value: list<u8>
    }
    
    variant p2p-event {
        subscribe(string),
        publish(p2p-publish-event),
        request(p2p-request-event),
        response(p2p-response-event),
        put(p2p-put-event)
    }
 }