package idp2p:p2p;

interface id-store {
    get: func(id: list<u8>) -> list<u8>;
    put: func(id: list<u8>, value: list<u8>);
    remove: func(id: list<u8>);
}

world idp2p-p2p {
    import id-store;
    import host: interface {
        call-func: func(id: string, method: string, args: list<u8>) -> result<list<u8>, string>;
    }
    export handle-message: func(topic: string, message: list<u8>) -> result<list<u8>, string>;
}