[package]
name = "idp2p_didcomm"
version = "0.1.0"
edition = "2021"

[dependencies]
x25519-dalek = "1.2.0"
chacha20poly1305 = "0.9.0"
serde = { version = "1.0.130", features = ["derive"] }
idp2p_common = { version = "0.1.0", path = "../idp2p-common" }